version: '3.2'

services:
  server:
    build: .
    container_name: jumia-bot-server
    ports:
      - "5000:5050"
      - "8000:8008"
    volumes:
      - type: bind
        source: .
        target: /var/www/
    restart: "no"
    command: sh run.sh
    depends_on:
      - mongo

  mongo:
    restart: on-failure
    container_name: mongo-db
    image: mongo
    volumes:
      - type: volume
        source: ./database/
        target: /data/db/
    ports:
      - "27072:27017"