 version: '3.7'

services:
  server:
    build: .
    container_name: jumia-bot-server
    env_file: .env
    environment:
      -SCRAPER_TRIGGER=/var/www/trigger-scraper.sh
      -PYTHONENV=production
      -MONGODB_URI=mongodb://localhost:27072/jumia_catalog-db
    port:
      - "5000":"5050"
      - "8000":"8008"
    stop_grace_period: 1m
    volumes:
      - type: bind
        source: ./
        target: /var/www
    restart: "no"
    command: sh run.sh

  mongo:
    restart: on-failure
    container_name: mongo-db
    image: mongo
    volumes:
      - /var/www/jumia-bot/data:/data/db
    ports:
      - "27072:27017"