version: '3.2'

services:
  server:
    build: .
    container_name: jumia-bot-server
    environment:
      - SCRAPER_TRIGGER="/var/www/trigger-scraper.sh"
      - PYTHONENV="production"
      - MONGODB_URI="mongodb://localhost:27072/jumia_catalog-db"
    ports:
      - "5000:5050"
      - "8000:8008"
    volumes:
      - type: bind
        source: .
        target: /var/www/html/node_modules
    restart: "no"
    command: sh run.sh

  mongo:
    restart: on-failure
    container_name: mongo-db
    image: mongo
    volumes:
      - /var/www/jumia-bot/data:/data/db
    ports:
      - "27072:27017"